
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(482, 422)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.algorithm = QtGui.QComboBox(self.centralwidget)
        self.algorithm.setObjectName(_fromUtf8("algorithm"))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.addItem(_fromUtf8(""))

        # I added one more item here
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.setCurrentIndex(4)

        # added algorithm HS-IPSO-GS
        self.algorithm.addItem(_fromUtf8(""))
        self.algorithm.setCurrentIndex(5)

        self.verticalLayout.addWidget(self.algorithm)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.execNum = QtGui.QSpinBox(self.centralwidget)
        self.execNum.setMinimum(1)
        self.execNum.setMaximum(1000)
        self.execNum.setObjectName(_fromUtf8("execNum"))
        self.verticalLayout.addWidget(self.execNum)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.checktime_yes = QtGui.QRadioButton(self.centralwidget)
        self.checktime_yes.setEnabled(True)
        self.checktime_yes.setCheckable(True)

        # I changed True on False it because I need False by default
        self.checktime_yes.setChecked(False)

        self.checktime_yes.setObjectName(_fromUtf8("checktime_yes"))
        self.verticalLayout_2.addWidget(self.checktime_yes)
        self.checktime_no = QtGui.QRadioButton(self.centralwidget)

        # I changed True on False it because I need False by default
        self.checktime_no.setChecked(True)

        self.checktime_no.setObjectName(_fromUtf8("checktime_no"))
        self.verticalLayout_2.addWidget(self.checktime_no)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.algconfname = QtGui.QLineEdit(self.centralwidget)
        self.algconfname.setObjectName(_fromUtf8("algconfname"))
        self.horizontalLayout_2.addWidget(self.algconfname)
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sysconfname = QtGui.QLineEdit(self.centralwidget)
        self.sysconfname.setObjectName(_fromUtf8("sysconfname"))
        self.horizontalLayout.addWidget(self.sysconfname)
        self.toolButton_2 = QtGui.QToolButton(self.centralwidget)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_4.addWidget(self.label_15)
        self.result_filename = QtGui.QLineEdit(self.centralwidget)
        self.result_filename.setObjectName(_fromUtf8("result_filename"))
        self.verticalLayout_4.addWidget(self.result_filename)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.mincost = QtGui.QLabel(self.centralwidget)
        self.mincost.setObjectName(_fromUtf8("mincost"))
        self.horizontalLayout_8.addWidget(self.mincost)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.maxcost = QtGui.QLabel(self.centralwidget)
        self.maxcost.setObjectName(_fromUtf8("maxcost"))
        self.horizontalLayout_9.addWidget(self.maxcost)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.limitcost = QtGui.QLineEdit(self.centralwidget)
        self.limitcost.setObjectName(_fromUtf8("limitcost"))
        self.horizontalLayout_7.addWidget(self.limitcost)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.mintime = QtGui.QLabel(self.centralwidget)
        self.mintime.setObjectName(_fromUtf8("mintime"))
        self.horizontalLayout_5.addWidget(self.mintime)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.maxtime = QtGui.QLabel(self.centralwidget)
        self.maxtime.setObjectName(_fromUtf8("maxtime"))
        self.horizontalLayout_4.addWidget(self.maxtime)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.limittimes = QtGui.QLineEdit(self.centralwidget)
        self.limittimes.setObjectName(_fromUtf8("limittimes"))
        self.horizontalLayout_6.addWidget(self.limittimes)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.use_metamodels = QtGui.QCheckBox(self.centralwidget)
        self.use_metamodels.setObjectName(_fromUtf8("use_metamodels"))
        self.verticalLayout_7.addWidget(self.use_metamodels)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_7.addWidget(self.label_3)
        self.metamodel = QtGui.QComboBox(self.centralwidget)
        self.metamodel.setEnabled(False)
        self.metamodel.setObjectName(_fromUtf8("metamodel"))
        self.metamodel.addItem(_fromUtf8(""))
        self.metamodel.addItem(_fromUtf8(""))
        self.metamodel.addItem(_fromUtf8(""))
        self.metamodel.addItem(_fromUtf8(""))
        self.metamodel.addItem(_fromUtf8(""))
        self.metamodel.addItem(_fromUtf8(""))
        self.verticalLayout_7.addWidget(self.metamodel)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_7.addWidget(self.label_14)
        self.popControl = QtGui.QSpinBox(self.centralwidget)
        self.popControl.setEnabled(False)
        self.popControl.setMaximum(100)
        self.popControl.setSingleStep(10)
        self.popControl.setProperty("value", 50)
        self.popControl.setObjectName(_fromUtf8("popControl"))
        self.verticalLayout_7.addWidget(self.popControl)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.metamodels_button = QtGui.QPushButton(self.centralwidget)
        self.metamodels_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pics/pics/chart_line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.metamodels_button.setIcon(icon)
        self.metamodels_button.setObjectName(_fromUtf8("metamodels_button"))
        self.horizontalLayout_3.addWidget(self.metamodels_button)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionEdit = QtGui.QAction(MainWindow)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionSave_2 = QtGui.QAction(MainWindow)
        self.actionSave_2.setObjectName(_fromUtf8("actionSave_2"))
        self.actionSave_as_2 = QtGui.QAction(MainWindow)
        self.actionSave_as_2.setObjectName(_fromUtf8("actionSave_as_2"))
        self.actionOpen_2 = QtGui.QAction(MainWindow)
        self.actionOpen_2.setObjectName(_fromUtf8("actionOpen_2"))
        self.actionEdit_2 = QtGui.QAction(MainWindow)
        self.actionEdit_2.setObjectName(_fromUtf8("actionEdit_2"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Run)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.OpenAlgConf)
        QtCore.QObject.connect(self.toolButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.OpenSysConf)
        QtCore.QObject.connect(self.algconfname, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.LoadAlgConf)
        QtCore.QObject.connect(self.sysconfname, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainWindow.LoadSysConf)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Random)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.SaveSysConf)
        QtCore.QObject.connect(self.limitcost, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.InputCostLimit)
        QtCore.QObject.connect(self.limittimes, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.InputTimeLimits)
        QtCore.QObject.connect(self.checktime_no, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.no_checked)
        QtCore.QObject.connect(self.checktime_yes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.yes_checked)
        QtCore.QObject.connect(self.use_metamodels, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.LoadSysConf)
        QtCore.QObject.connect(self.use_metamodels, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.use_metamodels_checked)
        QtCore.QObject.connect(self.metamodels_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.ShowMetamodelRes)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Select Algorithm:", None))
        self.algorithm.setItemText(0, _translate("MainWindow", "Genetic Algorithm", None))
        self.algorithm.setItemText(1, _translate("MainWindow", "Hybrid Genetic Algorithm", None))
        self.algorithm.setItemText(2, _translate("MainWindow", "Greedy Algorithm", None))
        self.algorithm.setItemText(3, _translate("MainWindow", "Simulated Annealing", None))
        # I added my new mega-algorithm here
        self.algorithm.setItemText(4, _translate("MainWindow", "Immune Algorithm", None))
        # I added my algo here
        self.algorithm.setItemText(5, _translate("MainWindow", "HS-IPSO-GS", None))

        self.label_2.setText(_translate("MainWindow", "Number of executions:", None))
        self.label_4.setText(_translate("MainWindow", "Check Time:", None))
        self.checktime_yes.setText(_translate("MainWindow", "Yes", None))
        self.checktime_no.setText(_translate("MainWindow", "No", None))
        self.label_5.setText(_translate("MainWindow", "File with algorithm settings:", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.label_6.setText(_translate("MainWindow", "System config file:", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.label_15.setText(_translate("MainWindow", "Result filename:", None))
        self.label_7.setText(_translate("MainWindow", "System Configuration:", None))
        self.label_9.setText(_translate("MainWindow", "Min Cost:", None))
        self.mincost.setText(_translate("MainWindow", "--", None))
        self.label_8.setText(_translate("MainWindow", "Max Cost:", None))
        self.maxcost.setText(_translate("MainWindow", "--", None))
        self.label_10.setText(_translate("MainWindow", "Cost Limit:", None))
        self.label_12.setText(_translate("MainWindow", "Min Times:", None))
        self.mintime.setText(_translate("MainWindow", "--", None))
        self.label_11.setText(_translate("MainWindow", "Max Times:", None))
        self.maxtime.setText(_translate("MainWindow", "--", None))
        self.label_13.setText(_translate("MainWindow", "Times Limits:", None))
        self.pushButton_2.setText(_translate("MainWindow", "Random", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save as ...", None))
        self.use_metamodels.setText(_translate("MainWindow", "Use metamodels", None))
        self.label_3.setText(_translate("MainWindow", "Metamodel:", None))
        self.metamodel.setItemText(0, _translate("MainWindow", "Averaging", None))
        self.metamodel.setItemText(1, _translate("MainWindow", "KNearestNeighbours", None))
        self.metamodel.setItemText(2, _translate("MainWindow", "Neural Network", None))
        self.metamodel.setItemText(3, _translate("MainWindow", "Support Vector Regression", None))
        self.metamodel.setItemText(4, _translate("MainWindow", "Linear Regression", None))
        self.metamodel.setItemText(5, _translate("MainWindow", "Random", None))
        self.label_14.setText(_translate("MainWindow", "Population control percent:", None))
        self.pushButton.setText(_translate("MainWindow", "Run", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as ...", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionEdit.setText(_translate("MainWindow", "Edit", None))
        self.actionSave_2.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as_2.setText(_translate("MainWindow", "Save as ...", None))
        self.actionOpen_2.setText(_translate("MainWindow", "Open", None))
        self.actionEdit_2.setText(_translate("MainWindow", "Edit", None))

import resources_rc
